! expanse.h — reusable pool for runtime-grown worlds (Path A). CC0.
! GENERATED by gen_expanse.mjs — do not edit by hand; change the generator.
! Include AFTER VerbLib and BEFORE Grammar in the host .inf.
! The proven spike pattern (byte-buffer names matched by parse_name) scaled to a
! flat pool: every blank carries a 'slot' index into shared buffer arrays.

Constant XP_NBUF = 32;
Constant XP_RDBUF = 200;
Constant XP_ODBUF = 120;
Constant XP_ROOMS = 48;
Constant XP_OBJS = 96;

Array XP_RoomName -> XP_ROOMS * XP_NBUF;
Array XP_RoomDesc -> XP_ROOMS * XP_RDBUF;
Array XP_ObjName  -> XP_OBJS * XP_NBUF;
Array XP_ObjDesc  -> XP_OBJS * XP_ODBUF;

Global XP_lastroom = 0;
Global XP_lastobj  = 0;

! --- buffer address helpers ---
[ XP_RNm o; return XP_RoomName + o.slot * XP_NBUF; ];
[ XP_RDs o; return XP_RoomDesc + o.slot * XP_RDBUF; ];
[ XP_ONm o; return XP_ObjName  + o.slot * XP_NBUF; ];
[ XP_ODs o; return XP_ObjDesc  + o.slot * XP_ODBUF; ];

! --- shared text helpers (proven in the spike) ---
[ XP_PrintBuf arr i len; len = arr->0; for (i=1:i<=len:i++) print (char) arr->i; ];
[ XP_CopyWord wx arr cap   ad ln i;
   ad = WordAddress(wx); ln = WordLength(wx); if (ln > cap-1) ln = cap-1;
   arr->0 = ln; for (i=0:i<ln:i++) arr->(i+1) = ad->i; ];
[ XP_WordEq wx arr   ad ln i;
   ad = WordAddress(wx); ln = WordLength(wx);
   if (ln ~= arr->0) rfalse;
   for (i=0:i<ln:i++) if (ad->i ~= arr->(i+1)) rfalse; rtrue; ];
! Copy the tail (words wstart..num_words), space-joined, into a buffer.
[ XP_CopyTail wstart arr cap   w ad ln i p;
   p = 0;
   for (w=wstart : w<=num_words : w++) {
      if (p > 0 && p < cap-1) { arr->(p+1) = ' '; p++; }
      ad = WordAddress(w); ln = WordLength(w);
      for (i=0 : i<ln && p<cap-1 : i++) { arr->(p+1) = ad->i; p++; }
   }
   arr->0 = p;
];
! Direction code from the first letter of word wx (n/s/e/w/u/d, full or abbrev).
[ XP_DirCode wx   ad;
   ad = WordAddress(wx);
   switch (ad->0) {
      'n': return 1; 's': return 2; 'e': return 3;
      'w': return 4; 'u': return 5; 'd': return 6;
   }
   return 0;
];
[ XP_TakeFlag wx   ad; ad = WordAddress(wx); if (ad->0 == '1') rtrue; rfalse; ];

! --- classes ---
Class BlankRoom
  with slot 0,
       n_to 0, s_to 0, e_to 0, w_to 0, u_to 0, d_to 0,
       used false,
       short_name [; if ((XP_RNm(self))->0 == 0) print "somewhere"; else XP_PrintBuf(XP_RNm(self)); rtrue; ],
       description [; if ((XP_RDs(self))->0 == 0) "An undefined space."; XP_PrintBuf(XP_RDs(self)); new_line; rtrue; ],
       parse_name [ c; c=0; while (wn <= num_words && XP_WordEq(wn, XP_RNm(self))) { wn++; c++; } return c; ],
  has light;

Class BlankObject
  with slot 0,
       used false,
       takeable true,
       short_name [; if ((XP_ONm(self))->0 == 0) print "thing"; else XP_PrintBuf(XP_ONm(self)); rtrue; ],
       description [; if ((XP_ODs(self))->0 == 0) "Nothing special."; XP_PrintBuf(XP_ODs(self)); new_line; rtrue; ],
       parse_name [ c; c=0; while (wn <= num_words && XP_WordEq(wn, XP_ONm(self))) { wn++; c++; } return c; ],
       before [; Take: if (self.takeable == false) "That is fixed in place."; ],
  has ;

! --- pool instances (generated) ---
BlankRoom xroom_0 with slot 0;
BlankRoom xroom_1 with slot 1;
BlankRoom xroom_2 with slot 2;
BlankRoom xroom_3 with slot 3;
BlankRoom xroom_4 with slot 4;
BlankRoom xroom_5 with slot 5;
BlankRoom xroom_6 with slot 6;
BlankRoom xroom_7 with slot 7;
BlankRoom xroom_8 with slot 8;
BlankRoom xroom_9 with slot 9;
BlankRoom xroom_10 with slot 10;
BlankRoom xroom_11 with slot 11;
BlankRoom xroom_12 with slot 12;
BlankRoom xroom_13 with slot 13;
BlankRoom xroom_14 with slot 14;
BlankRoom xroom_15 with slot 15;
BlankRoom xroom_16 with slot 16;
BlankRoom xroom_17 with slot 17;
BlankRoom xroom_18 with slot 18;
BlankRoom xroom_19 with slot 19;
BlankRoom xroom_20 with slot 20;
BlankRoom xroom_21 with slot 21;
BlankRoom xroom_22 with slot 22;
BlankRoom xroom_23 with slot 23;
BlankRoom xroom_24 with slot 24;
BlankRoom xroom_25 with slot 25;
BlankRoom xroom_26 with slot 26;
BlankRoom xroom_27 with slot 27;
BlankRoom xroom_28 with slot 28;
BlankRoom xroom_29 with slot 29;
BlankRoom xroom_30 with slot 30;
BlankRoom xroom_31 with slot 31;
BlankRoom xroom_32 with slot 32;
BlankRoom xroom_33 with slot 33;
BlankRoom xroom_34 with slot 34;
BlankRoom xroom_35 with slot 35;
BlankRoom xroom_36 with slot 36;
BlankRoom xroom_37 with slot 37;
BlankRoom xroom_38 with slot 38;
BlankRoom xroom_39 with slot 39;
BlankRoom xroom_40 with slot 40;
BlankRoom xroom_41 with slot 41;
BlankRoom xroom_42 with slot 42;
BlankRoom xroom_43 with slot 43;
BlankRoom xroom_44 with slot 44;
BlankRoom xroom_45 with slot 45;
BlankRoom xroom_46 with slot 46;
BlankRoom xroom_47 with slot 47;

BlankObject xobj_0 with slot 0;
BlankObject xobj_1 with slot 1;
BlankObject xobj_2 with slot 2;
BlankObject xobj_3 with slot 3;
BlankObject xobj_4 with slot 4;
BlankObject xobj_5 with slot 5;
BlankObject xobj_6 with slot 6;
BlankObject xobj_7 with slot 7;
BlankObject xobj_8 with slot 8;
BlankObject xobj_9 with slot 9;
BlankObject xobj_10 with slot 10;
BlankObject xobj_11 with slot 11;
BlankObject xobj_12 with slot 12;
BlankObject xobj_13 with slot 13;
BlankObject xobj_14 with slot 14;
BlankObject xobj_15 with slot 15;
BlankObject xobj_16 with slot 16;
BlankObject xobj_17 with slot 17;
BlankObject xobj_18 with slot 18;
BlankObject xobj_19 with slot 19;
BlankObject xobj_20 with slot 20;
BlankObject xobj_21 with slot 21;
BlankObject xobj_22 with slot 22;
BlankObject xobj_23 with slot 23;
BlankObject xobj_24 with slot 24;
BlankObject xobj_25 with slot 25;
BlankObject xobj_26 with slot 26;
BlankObject xobj_27 with slot 27;
BlankObject xobj_28 with slot 28;
BlankObject xobj_29 with slot 29;
BlankObject xobj_30 with slot 30;
BlankObject xobj_31 with slot 31;
BlankObject xobj_32 with slot 32;
BlankObject xobj_33 with slot 33;
BlankObject xobj_34 with slot 34;
BlankObject xobj_35 with slot 35;
BlankObject xobj_36 with slot 36;
BlankObject xobj_37 with slot 37;
BlankObject xobj_38 with slot 38;
BlankObject xobj_39 with slot 39;
BlankObject xobj_40 with slot 40;
BlankObject xobj_41 with slot 41;
BlankObject xobj_42 with slot 42;
BlankObject xobj_43 with slot 43;
BlankObject xobj_44 with slot 44;
BlankObject xobj_45 with slot 45;
BlankObject xobj_46 with slot 46;
BlankObject xobj_47 with slot 47;
BlankObject xobj_48 with slot 48;
BlankObject xobj_49 with slot 49;
BlankObject xobj_50 with slot 50;
BlankObject xobj_51 with slot 51;
BlankObject xobj_52 with slot 52;
BlankObject xobj_53 with slot 53;
BlankObject xobj_54 with slot 54;
BlankObject xobj_55 with slot 55;
BlankObject xobj_56 with slot 56;
BlankObject xobj_57 with slot 57;
BlankObject xobj_58 with slot 58;
BlankObject xobj_59 with slot 59;
BlankObject xobj_60 with slot 60;
BlankObject xobj_61 with slot 61;
BlankObject xobj_62 with slot 62;
BlankObject xobj_63 with slot 63;
BlankObject xobj_64 with slot 64;
BlankObject xobj_65 with slot 65;
BlankObject xobj_66 with slot 66;
BlankObject xobj_67 with slot 67;
BlankObject xobj_68 with slot 68;
BlankObject xobj_69 with slot 69;
BlankObject xobj_70 with slot 70;
BlankObject xobj_71 with slot 71;
BlankObject xobj_72 with slot 72;
BlankObject xobj_73 with slot 73;
BlankObject xobj_74 with slot 74;
BlankObject xobj_75 with slot 75;
BlankObject xobj_76 with slot 76;
BlankObject xobj_77 with slot 77;
BlankObject xobj_78 with slot 78;
BlankObject xobj_79 with slot 79;
BlankObject xobj_80 with slot 80;
BlankObject xobj_81 with slot 81;
BlankObject xobj_82 with slot 82;
BlankObject xobj_83 with slot 83;
BlankObject xobj_84 with slot 84;
BlankObject xobj_85 with slot 85;
BlankObject xobj_86 with slot 86;
BlankObject xobj_87 with slot 87;
BlankObject xobj_88 with slot 88;
BlankObject xobj_89 with slot 89;
BlankObject xobj_90 with slot 90;
BlankObject xobj_91 with slot 91;
BlankObject xobj_92 with slot 92;
BlankObject xobj_93 with slot 93;
BlankObject xobj_94 with slot 94;
BlankObject xobj_95 with slot 95;

! --- free-slot finders ---
[ XP_FreeRoom o; objectloop (o ofclass BlankRoom) if (o.used == false) return o; return 0; ];
[ XP_FreeObj  o; objectloop (o ofclass BlankObject) if (o.used == false) return o; return 0; ];

! --- exit linking (both ways) ---
[ XP_LinkExits fromR toR code;
   switch (code) {
      1: fromR.n_to = toR; toR.s_to = fromR;
      2: fromR.s_to = toR; toR.n_to = fromR;
      3: fromR.e_to = toR; toR.w_to = fromR;
      4: fromR.w_to = toR; toR.e_to = fromR;
      5: fromR.u_to = toR; toR.d_to = fromR;
      6: fromR.d_to = toR; toR.u_to = fromR;
   }
];

! --- meta-verbs the engine drives ---
! xroom <dir> <name>  : claim a blank room <dir> of the player's room, name it, link both ways.
[ XroomSub  newR code;
   code = XP_DirCode(2);
   if (code == 0) "xroom bad-direction";
   newR = XP_FreeRoom();
   if (newR == 0) "xroom no-free-room";
   XP_CopyWord(3, XP_RNm(newR), XP_NBUF);
   newR.used = true;
   XP_LinkExits(location, newR, code);
   XP_lastroom = newR;
   "xroom ok";
];
! xdesc <words...> : set the description of the most-recently-created room.
[ XrdescSub;
   if (XP_lastroom == 0) "xdesc no-room";
   XP_CopyTail(2, XP_RDs(XP_lastroom), XP_RDBUF);
   "xdesc ok";
];
! xobj <flag> <name> : claim a blank object into the last room; flag 1 = takeable.
[ XobjSub  newO;
   if (XP_lastroom == 0) "xobj no-room";
   newO = XP_FreeObj();
   if (newO == 0) "xobj no-free-obj";
   newO.takeable = XP_TakeFlag(2);
   XP_CopyWord(3, XP_ONm(newO), XP_NBUF);
   newO.used = true;
   move newO to XP_lastroom;
   XP_lastobj = newO;
   "xobj ok";
];
! xodesc <words...> : set the description of the most-recently-created object.
[ XodescSub;
   if (XP_lastobj == 0) "xodesc no-obj";
   XP_CopyTail(2, XP_ODs(XP_lastobj), XP_ODBUF);
   "xodesc ok";
];

Verb 'xroom'  * topic -> Xroom;
Verb 'xdesc'  * topic -> Xrdesc;
Verb 'xobj'   * topic -> Xobj;
Verb 'xodesc' * topic -> Xodesc;
